### ISSUE TITLE
Up Next Service 

### ISSUE THREAD

**Issue by weebl101** [MediaBrowser/plugin.video.emby#278]
Hello,

I was just wondering if you were able to shed some light. Unfortunately, the up next service won’t automatically play the next episode since the patch that was applied two days ago. 

Thanks in advance for any help you can provide.

**Comment by angelblue05** [comment]
Not something I’m seeing. Provide your Kodi log, thanks!

**Comment by angelblue05** [comment]
Restart Kodi, you'll see a new patch applied. This should resolve the issue.

**Comment by weebl101** [comment]
Thanks for the response. The patch has been applied, but still not auto-playing. I will provide my log today.

Thanks again

**Comment by angelblue05** [comment]
Thanks, I have no been able to replicate with the latest fix.

**Comment by weebl101** [comment]
I am using Arctic Xephyr Leia Mod, and I was also using Titan Mod, it had been working on both. The notification box appears in the right corner, and works when ok is pressed, just not the auto-play. Log is provided below.

https://drive.google.com/open?id=15CNJZtPyGJleKJQjzrz-AcDcegP7_As2

**Comment by angelblue05** [comment]
Thanks, I’ll check your log and keep you posted.

**Comment by weebl101** [comment]
Thank you

**Comment by angelblue05** [comment]
I’ll have a fix out later today.

**Comment by weebl101** [comment]
Awesome, thank you for your help. 

Thanks also for the addon, it is truely amazing.

**Comment by angelblue05** [comment]
@weebl101 I've just posted 4.1.2. Restart Kodi to be sure. Let me know if the issue persists. I have reworked the logic for up next, so hopefully, it behaves better now.

**Comment by weebl101** [comment]
@angelblue05 I have updated and the issue is still persisting. 

It seems that auto-play will only work with unwatched videos, even if the include watched items in the settings is selected.

**Comment by angelblue05** [comment]
So it’s different now? It does work but only for unwatched content? Provide an updated Kodi log, thanks.

**Comment by angelblue05** [comment]
Did you restart Kodi too?

Sorry it’s difficult to troubleshoot as I’m not getting any issues on my side. The playlist is no longer cleared, so that should have resolved it.

**Comment by weebl101** [comment]
I am currently just reinstalling everything to see if that rectifies it. I’ll let you know.

**Comment by angelblue05** [comment]
You didn’t need to do that... I doubt itmll chante anything.

**Comment by angelblue05** [comment]
I have my co dev testing, he’s seeing an issue as well. It looks like a race condition with Kodi stopping playback and the add-on starting the playback. They happens so quickly, that Kodi stops playback of the new item. If you check the current playlist, you’ll see the next item is there, unplayed.

**Comment by weebl101** [comment]
Is there a way to fix it?

**Comment by weebl101** [comment]
I can see two items just sitting in the playlist.

**Comment by angelblue05** [comment]
I will let you know as soon as this has been addressed. Thanks for your patience :)

**Comment by weebl101** [comment]
Awesome. Totally fine, thank you for all your help.

**Comment by angelblue05** [comment]
Alright, this time it should be fixed, Restart Emby for Kodi (or Kodi). Let me know if it works now, at least my co dev doesn't see it happen anymore.

**Comment by weebl101** [comment]
Lol, ok will do. Will try tomorrow and let you know.

**Comment by weebl101** [comment]
@angelblue05 It appears to be working, thank you for all your help. 

I have one question. Meta Data on one of my shows has gone whack, is there a way to refresh just the single show? I click Information and Refresh, and a dialog box comes up asking for the name of the show, but when I enter it, it does nothing, the dialog box will just appear again

**Comment by angelblue05** [comment]
Glad to hear it is resolved.

For the refresh, you want to use the refresh under emby options rather than the refresh via Kodi. This will trigger a refresh server side and update the metadata shortly after.

**Comment by weebl101** [comment]
Me too, thank you so much again for tracking down a fix. Much appreciated
